// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: device.sql

package dbrepo

import (
	"context"
)

const createNewDevice = `-- name: CreateNewDevice :one
INSERT INTO
    devices (
        project_id,
        name,
        description,
        client_device_id,
        custom_attributes
    )
VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type CreateNewDeviceParams struct {
	ProjectID        int32   `db:"project_id" json:"project_id"`
	Name             string  `db:"name" json:"name"`
	Description      *string `db:"description" json:"description"`
	ClientDeviceID   string  `db:"client_device_id" json:"client_device_id"`
	CustomAttributes []byte  `db:"custom_attributes" json:"custom_attributes"`
}

func (q *Queries) CreateNewDevice(ctx context.Context, arg *CreateNewDeviceParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNewDevice,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.ClientDeviceID,
		arg.CustomAttributes,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
