// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: projects.sql

package dbrepo

import (
	"context"
)

const createNewProjects = `-- name: CreateNewProjects :one
INSERT INTO
    projects (
        name,
        alias,
        description,
        settings
    )
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateNewProjectsParams struct {
	Name        string  `db:"name" json:"name"`
	Alias       string  `db:"alias" json:"alias"`
	Description *string `db:"description" json:"description"`
	Settings    []byte  `db:"settings" json:"settings"`
}

func (q *Queries) CreateNewProjects(ctx context.Context, arg *CreateNewProjectsParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNewProjects,
		arg.Name,
		arg.Alias,
		arg.Description,
		arg.Settings,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getProjectByAlias = `-- name: GetProjectByAlias :one
SELECT id, alias FROM projects WHERE alias = $1
`

type GetProjectByAliasRow struct {
	ID    int32  `db:"id" json:"id"`
	Alias string `db:"alias" json:"alias"`
}

func (q *Queries) GetProjectByAlias(ctx context.Context, alias string) (*GetProjectByAliasRow, error) {
	row := q.db.QueryRow(ctx, getProjectByAlias, alias)
	var i GetProjectByAliasRow
	err := row.Scan(&i.ID, &i.Alias)
	return &i, err
}

const getProjects = `-- name: GetProjects :many
SELECT
    id,
    name,
    alias,
    description,
    settings
FROM projects
ORDER BY created_at ASC
`

type GetProjectsRow struct {
	ID          int32   `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Alias       string  `db:"alias" json:"alias"`
	Description *string `db:"description" json:"description"`
	Settings    []byte  `db:"settings" json:"settings"`
}

func (q *Queries) GetProjects(ctx context.Context) ([]*GetProjectsRow, error) {
	rows, err := q.db.Query(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetProjectsRow
	for rows.Next() {
		var i GetProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Alias,
			&i.Description,
			&i.Settings,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
